# Generated by Django 4.2.7 on 2024-02-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusterconsumption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumerconsumption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='forecastingconsumerconsumption',
            unique_together=set(),
        ),
    ]
