# Generated by Django 4.2.7 on 2024-02-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_clusterconsumption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusterconsumption',
            unique_together={('cluster', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='consumerconsumption',
            unique_together={('consumer', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='forecastingconsumerconsumption',
            unique_together={('consumer', 'datetime')},
        ),
    ]
