# Generated by Django 4.2.7 on 2024-02-12 09:21

from django.db import migrations
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_alter_clusterconsumption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterconsumption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consumerconsumption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='forecastingconsumerconsumption',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='clusterconsumption',
            name='backend_app_datetim_7b3dbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='clusterconsumption',
            name='backend_app_cluster_f6ae5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='consumerconsumption',
            name='backend_app_datetim_d69907_idx',
        ),
        migrations.RemoveIndex(
            model_name='consumerconsumption',
            name='backend_app_consume_f7038e_idx',
        ),
        migrations.RemoveIndex(
            model_name='forecastingconsumerconsumption',
            name='backend_app_datetim_4af3de_idx',
        ),
        migrations.RemoveIndex(
            model_name='forecastingconsumerconsumption',
            name='backend_app_consume_192eb4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clusterconsumption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumerconsumption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='forecastingconsumerconsumption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clusterconsumption',
            name='datetime',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour'),
        ),
        migrations.AlterField(
            model_name='consumerconsumption',
            name='datetime',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour'),
        ),
        migrations.AlterField(
            model_name='forecastingconsumerconsumption',
            name='datetime',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour'),
        ),
    ]
