# Generated by Django 4.2.7 on 2024-02-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_alter_clusterconsumption_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterdailyconsumptionaggregate',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.AlterUniqueTogether(
            name='clusterdailyconsumptionaggregate',
            unique_together={('cluster', 'day')},
        ),
    ]
