# Generated by Django 4.2.7 on 2024-02-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_rename_day_of_week_clusterdailyconsumptionaggregate_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerdailyconsumptionaggregate',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.AlterUniqueTogether(
            name='consumerdailyconsumptionaggregate',
            unique_together={('consumer', 'day')},
        ),
    ]
