# Generated by Django 4.2.7 on 2024-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_rename_day_of_week_consumerdailyconsumptionaggregate_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mape', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rmse', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mse', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
