# Generated by Django 4.2.7 on 2024-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_forecastingmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('consumer', 'Consumer'), ('provider', 'Provider'), ('worker', 'Worker')], max_length=10, null=True),
        ),
    ]
