# Generated by Django 4.2.7 on 2024-03-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusterconsumption',
            unique_together={('cluster', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='consumerconsumption',
            unique_together={('consumer', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='forecastingconsumerconsumption',
            unique_together={('consumer', 'datetime')},
        ),
    ]
